"""AST validator editing command."""

import sys
from pathlib import Path

import rich_click as click

from determystic.configs.project import ProjectConfigManager, ValidatorFile
from determystic.agents.local_agent import (
    LocalAgentSelectionError,
    select_local_agent,
    stream_edit_validator_with_local_agent,
)
from determystic.cli import ui
from determystic.io import async_to_sync

console = ui.console


@click.command()
@click.argument("name", required=False)
@click.option(
    "--path",
    type=click.Path(path_type=Path),
    default=None,
    help="Path to the project containing the validator.",
)
@async_to_sync
async def edit_validator_command(name: str | None, path: Path | None):
    """Run the interactive validator editing workflow."""

    if path:
        ProjectConfigManager.set_runtime_custom_path(path)

    ui.banner("edit-validator")

    config_manager = ProjectConfigManager.load_from_disk()

    custom_validators = config_manager.get_custom_validators()
    if not custom_validators:
        ui.warning("No custom validators found in this project.")
        ui.hint("run 'determystic new-validator' to create your first validator")
        sys.exit(1)

    try:
        selected_agent = select_local_agent(config_manager.settings.validator_agent)
    except LocalAgentSelectionError as e:
        ui.error(str(e))
        sys.exit(1)

    # Resolve which validator to edit
    if name is None:
        name = await _prompt_for_validator(custom_validators)
    elif name not in custom_validators:
        ui.error(f"Validator '{name}' not found in this project.")
        ui.hint(f"available validators: {', '.join(sorted(custom_validators))}")
        sys.exit(1)

    validator_file = custom_validators[name]

    # Load the current validator contents from disk
    validator_path = config_manager.resolve_project_path(validator_file.validator_path)
    if not validator_path.exists():
        ui.error(f"Validator file is missing on disk: {validator_path}")
        sys.exit(1)
    validation_contents = validator_path.read_text()

    test_contents = ""
    if validator_file.test_path:
        test_path = config_manager.resolve_project_path(validator_file.test_path)
        if test_path.exists():
            test_contents = test_path.read_text()

    # Show the current validator
    ui.section(f"Current validator: {name}", step="1/2")
    if validator_file.description:
        ui.hint(validator_file.description)
    ui.code_block(validation_contents, title=name, line_numbers=True)

    # Get the requested changes
    ui.section("Describe the changes", step="2/2")
    change_request = await ui.multiline_input(
        "How should the validator change?",
        description="New patterns to catch, false positives to fix, etc.",
    )

    if not change_request:
        ui.error("No changes described.")
        sys.exit(1)

    # Confirm before proceeding
    console.print()
    ui.detail("validator", name)
    ui.detail("changes", change_request)
    console.print()

    if not await ui.confirm("Apply these changes?"):
        ui.hint("cancelled")
        sys.exit(0)

    # Run the agent
    console.print()
    ui.hint(f"handing off to {selected_agent} — it will edit and re-test the validator")
    console.print()

    final_event = await ui.render_agent_stream(
        stream_edit_validator_with_local_agent(
            validator_name=name,
            change_request=change_request,
            validation_contents=validation_contents,
            test_contents=test_contents,
            agent_name=selected_agent,
            description=validator_file.description,
        )
    )

    if not final_event:
        ui.error("No final event received from the agent.")
        sys.exit(1)

    updated_validation = final_event.deps.validation_contents
    updated_tests = final_event.deps.test_contents

    if not updated_validation:
        ui.warning("No updated files were generated by the agent.")
        return

    try:
        updated_file = config_manager.update_validation(
            name=name,
            validator_script=updated_validation,
            test_script=updated_tests,
        )

        # Save the config to disk
        config_manager.save_to_disk()

        console.print()
        ui.success("Validator updated")
        ui.detail("validator", updated_file.validator_path)
        if updated_file.test_path:
            ui.detail("tests", updated_file.test_path)
        console.print()

        # Show preview of the updated validator
        lines = updated_validation.split("\n")[:10]
        preview = "\n".join(lines)
        if len(updated_validation.split("\n")) > 10:
            preview += "\n..."

        ui.code_block(preview, title=name)

    except Exception as e:
        console.print(f"[error]Error saving validator files: {e}[/error]")


async def _prompt_for_validator(custom_validators: dict[str, ValidatorFile]) -> str:
    """Prompt for a validator with an arrow-key selection menu."""
    choices = [
        (validator_name, custom_validators[validator_name].description)
        for validator_name in sorted(custom_validators)
    ]
    return await ui.select_option("Which validator do you want to edit?", choices)
