"""AST validator creation command."""

import sys
from pathlib import Path
import re
from random import randint

import rich_click as click

from determystic.configs.project import ProjectConfigManager
from determystic.agents.local_agent import (
    LocalAgentSelectionError,
    select_local_agent,
    stream_create_validator_with_local_agent,
)
from determystic.cli import ui
from determystic.io import async_to_sync

console = ui.console


@click.command()
@click.argument("path", type=click.Path(path_type=Path), required=False)
@async_to_sync
async def new_validator_command(path: Path | None):
    """Run the interactive validator creation workflow."""

    if path:
        ProjectConfigManager.set_runtime_custom_path(path)

    ui.banner("new-validator")

    config_manager = ProjectConfigManager.load_from_disk()
    try:
        selected_agent = select_local_agent(config_manager.settings.validator_agent)
    except LocalAgentSelectionError as e:
        ui.error(str(e))
        sys.exit(1)

    # Get code snippet from user
    ui.section("Paste the problematic code", step="1/3")
    code_snippet = await ui.multiline_input(
        "Bad Python code your agent generated",
        description="The validator will be built to flag this pattern.",
    )

    if not code_snippet:
        ui.error("No code provided.")
        sys.exit(1)

    ui.code_block(code_snippet, title="your code", line_numbers=True)

    # Get description of issues
    ui.section("Describe the issue", step="2/3")
    issue_description = await ui.text_input(
        "What should the validator detect in this code?",
        default="Detect all potential issues",
    )

    # Get validator name
    ui.section("Name the validator", step="3/3")
    raw_validator_name = await ui.text_input(
        "Validator name",
        description="A short descriptive slug, e.g. unused-variable-detector",
        default="custom_validator",
    )

    validator_name = _format_validator_name(raw_validator_name)

    # Show the formatted name if it changed
    if validator_name != raw_validator_name:
        ui.hint(f"formatted as {validator_name}")

    # Check if validator already exists
    existing_validators = list(config_manager.get_custom_validators().values())
    if any(v.name == validator_name for v in existing_validators):
        if not await ui.confirm(f"Validator '{validator_name}' already exists. Overwrite?", default=False):
            ui.hint("cancelled")
            sys.exit(0)

    # Confirm before proceeding
    console.print()
    ui.detail("name", validator_name)
    ui.detail("code", f"{len(code_snippet)} characters")
    ui.detail("detects", issue_description)
    console.print()

    if not await ui.confirm("Create this validator?"):
        ui.hint("cancelled")
        sys.exit(0)

    # Run the agent
    console.print()
    ui.hint(f"handing off to {selected_agent} — it will write and test the validator")
    console.print()

    final_event = await ui.render_agent_stream(
        stream_create_validator_with_local_agent(
            user_code=code_snippet,
            requirements=issue_description,
            agent_name=selected_agent,
        )
    )

    if not final_event:
        ui.error("No final event received from the agent.")
        sys.exit(1)

    validation_contents = final_event.deps.validation_contents
    test_contents = final_event.deps.test_contents

    # Save validator files and track them in pyproject.toml
    if not validation_contents:
        ui.warning("No files were generated by the agent.")
        return

    try:
        validator_file = config_manager.new_validation(
            name=validator_name,
            validator_script=validation_contents,
            test_script=test_contents or "",
            description=issue_description
        )

        # Save the config to disk
        config_manager.save_to_disk()

        console.print()
        ui.success("Validator saved")
        ui.detail("validator", validator_file.validator_path)
        if validator_file.test_path:
            ui.detail("tests", validator_file.test_path)
        console.print()

        # Show preview of the validator
        lines = validation_contents.split("\n")[:10]
        preview = "\n".join(lines)
        if len(validation_contents.split("\n")) > 10:
            preview += "\n..."

        ui.code_block(preview, title=validator_name)

    except Exception as e:
        console.print(f"[error]Error saving validator files: {e}[/error]")


def _format_validator_name(raw_validator_name: str) -> str:
    """
    Auto-format the name to be valid (replace spaces with hyphens, keep only valid chars)
    """
    # Replace spaces with hyphens, keep only letters, numbers, hyphens, and underscores
    validator_name = re.sub(r'[^a-zA-Z0-9_-]', '-', raw_validator_name.strip())
    # Replace multiple consecutive hyphens with single hyphen
    validator_name = re.sub(r'-+', '-', validator_name)
    # Remove leading/trailing hyphens
    validator_name = validator_name.strip('-')

    # Ensure the name is not empty after formatting
    if not validator_name:
        validator_name = f"custom_validator_{randint(1000, 9999)}"

    return validator_name
